### ISSUE TITLE
application_helper.rb links to this CodeForPDX github and not CodeForPortland

### ISSUE THREAD

**Issue by NerdBird** [codeforpdx/old_website#7]
Was looking through the website just now to learn more about the group. Noticed that this Github org wasn't as active as the website would indicate then found that you had another Org at https://github.com/CodeForPortland.

Is intended for the website to link to this repository and not the more active CodeForPortland Organization?

I made a branch with an update, before I realized I couldn't open a PR for this repo. :D

**Comment by NickSchimek** [comment]
@NerdBird Thanks for putting this in! You can always open PR's if you first fork the repo, push the changes up to your forked repo, and then submit PR.

-> Is intended for the website to link to this repository and not the more active CodeForPortland Organization?
To answer your question. It should link to this site `/codeforpdx` as the other one is in the process of moving all active repos over, and `codeforportland` will be archived.
